### ISSUE TITLE
Hello，Excuse me, Why do you want to divide the intrinsic of the eighty-first line of the fuse_depth file by 7.5, Hope to get your reply

### ISSUE THREAD

**Issue by HiRenZeHui** [Haonan-DONG/fusion_depth_mvs#1]
Hello，Excuse me, Why do you want to divide the intrinsic of the eighty-first line of the fuse_depth file by 7.5, Hope to get your reply

**Comment by Haonan-DONG** [comment]
Thanks for the interest of this repo. This script is designed for rgb-d depth reconstruction by a iPad Pro, where the resolutions of depth and the rgb image are 192*256 and 1440*1920, respectively. To fuse the depth and rgb for the same resolution, the rgb and  the intrinsic matrix are down-scaled by 7.5.
