### ISSUE TITLE
数据集制作

### ISSUE THREAD

**Issue by HiRenZeHui** [Haonan-DONG/fusion_depth_mvs#2]
你好，请问您的demo data的相机内外参数是用什么方法获得的呢。想自己做一份数据集试一下，期待您的回复。

**Comment by Haonan-DONG** [comment]
抱歉回复的比较晚，这个是通过对一个iPad Pro (带有tof深度传感器的那一款) 开发得到的demo数据，如果您希望通过ipad-pro rgb-d相机采集数据，转换为这个demo的格式，可以参考浙大3DV的ARKit开发教程进行开发 (https://github.com/zju3dv/NeuralRecon/blob/master/DEMO.md)，我之后会有计划对realsense相机的rgbd数据进行处理（类似于TUM格式的数据集），转化成mvs这种格式。

**Comment by Haonan-DONG** [comment]
closed
